using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace App.Core.Models.Users
{
    public class UserDataDto
    {
        public int UserId { get; set; }   // AutoGenerated
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string UserTypeName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public int? ZipCode { get; set; }
        public string ProfileImage { get; set; }

        public string CountryName { get; set; }
        public string StateName { get; set; }
    }
}
